# Generated by Django 3.2.4 on 2021-06-07 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_chat', '0002_auto_20210607_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicchatroom',
            name='users',
        ),
        migrations.AddField(
            model_name='publicchatroom',
            name='joiners',
            field=models.ManyToManyField(blank=True, help_text='users who are connected to the chat', related_name='chatrooms_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicchatroom',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_created', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicchatroommessage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_messages', to='public_chat.publicchatroom'),
        ),
        migrations.AlterField(
            model_name='publicchatroommessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
