# Generated by Django 3.2.4 on 2021-06-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0004_alter_publicchatroommessage_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publicchatroommessage',
            managers=[
            ],
        ),
    ]
